"""Add notifications to users

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-12 20:07:51.724601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("push_token", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "price_change_reminder", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "price_change_reminder")
    op.drop_column("users", "push_token")
    # ### end Alembic commands ###
