"""Add VehicleState model for Fleet Telemetry

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-13 09:30:56.811565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: Union[str, None] = "0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_states",
        sa.Column("vehicle_id", sa.String(length=32), nullable=False),
        sa.Column("charging_state", sa.String(length=32), nullable=True),
        sa.Column("battery_level", sa.Integer(), nullable=True),
        sa.Column("battery_range", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("charger_power", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("minutes_to_full_charge", sa.Integer(), nullable=True),
        sa.Column("charge_limit_soc", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("vehicle_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_states")
    # ### end Alembic commands ###
