"""Initial migration

Revision ID: 59d241768575
Revises: 
Create Date: 2026-06-12 15:52:38.441697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d241768575'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('threshold_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('auto_charge_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_table('charge_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_events_user_id'), 'charge_events', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('receipt', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tesla_accounts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('vehicle_vin', sa.String(length=32), nullable=True),
    sa.Column('vehicle_display_name', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tesla_accounts')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_charge_events_user_id'), table_name='charge_events')
    op.drop_table('charge_events')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
