"""Add vat_included to users

Revision ID: 5d93641379e8
Revises: 59d241768575
Create Date: 2026-06-12 16:13:45.109521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d93641379e8'
down_revision: Union[str, None] = '59d241768575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vat_included', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vat_included')
    # ### end Alembic commands ###
