"""Add google_id, apple_id, email

Revision ID: 62e62d95f5d7
Revises: facb8bab9c27
Create Date: 2026-06-13 05:06:46.068532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e62d95f5d7'
down_revision: Union[str, None] = 'facb8bab9c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('apple_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('users', 'device_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.alter_column('users', 'device_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'email')
    op.drop_column('users', 'apple_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
