"""Add home location to users

Revision ID: 6aaf6f306752
Revises: a94878e0dcb6
Create Date: 2026-06-12 19:07:12.497529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaf6f306752'
down_revision: Union[str, None] = 'a94878e0dcb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('home_latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('users', sa.Column('home_longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'home_longitude')
    op.drop_column('users', 'home_latitude')
    # ### end Alembic commands ###
