"""Add units to users

Revision ID: 7d5c1d88514e
Revises: 5d93641379e8
Create Date: 2026-06-12 16:36:07.537070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5c1d88514e'
down_revision: Union[str, None] = '5d93641379e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('units', sa.String(length=16), server_default='metric', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'units')
    # ### end Alembic commands ###
