"""Add price_with_vat to RegionPrice

Revision ID: a94878e0dcb6
Revises: 1d500af9ee6e
Create Date: 2026-06-12 18:02:56.067912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94878e0dcb6'
down_revision: Union[str, None] = '1d500af9ee6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region_prices', sa.Column('price_with_vat', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region_prices', 'price_with_vat')
    # ### end Alembic commands ###
